name       : qnapi
homepage   : http://qnapi.github.io/
version    : 0.1.9
release    : 4
source     :
    - https://github.com/QNapi/qnapi/releases/download/0.1.9/qnapi-0.1.9.tar.gz : ea1d5056e2bfbe9a2feea928388bd411bac64b9b19327c73946c7d4dd0c9ec9b
license    : GPL-2.0
component  : multimedia.video
summary    : Qt-based, multi-engine, multi-platform subtitle downloader
description: |
    QNapi is free software for automatic fetching subtitles for given movie file. It uses online databases such as NapiProjekt, OpenSubtitles and Napisy24.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
rundeps    :
    - ffmpeg
    - p7zip
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT="${installdir}"
